debug: true
server:
  port: 9999

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'

zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8888/relay
      sensitiveHeaders: Cookie,Set-Cookie

proxy:
  auth:
    loadBalanced: false
    routes:
      resource: oauth2
#      resource: none

security:
  oauth2:
    sso:
      loginPath: /dashboard/login
    client:
      clientId: 89630a412fa314777dc2
      clientSecret: c7a29ec26ec7805e78b496ea67cc13e5a9b8bcf0
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

    